### ISSUE TITLE
Error: funded too recently

### ISSUE THREAD

**Issue by ligi** [prysmaticlabs/prysm-testnet-site#108]
I want to try out the software again - but in step 2 got this:

![Selection_329](https://user-images.githubusercontent.com/111600/72765094-11c99b80-3beb-11ea-9b4f-21c20508781f.png)

but as you see: 0x37Af8A91Dc424dA37B822aC45935C7Ba65d824Ff does not have a goerli transacion. I changed the account to make sure this one was not used for prysm tests. I did some testing months ago - but with a different account.

**Comment by nisdas** [comment]
@ligi transferred the two issues to here, as this is the testnet site repo

**Comment by amaurer** [comment]
Same issue here - changed browsers (Brave and Chrome) - changed wallets - no joy.

**Comment by nisdas** [comment]
Hey guys , we just merged in a change which should help with this. 
https://github.com/prysmaticlabs/prysm/pull/4624. This would limit to being funded 5 times
in a day. You shouldnt be facing this anymore

**Comment by amaurer** [comment]
Yep, works for me now. Thanks!
