### ISSUE TITLE
security issue with the proposed key pair generation on our testnet site

### ISSUE THREAD

**Issue by shayzluf** [prysmaticlabs/prysm-testnet-site#113]
the terminal command ./prysm.sh validator accounts create --keystore-path=$HOME/validator --password= is saved in terminal history and can be retrieved easily.

it will be better to advise users to write the command ./prysm.sh validator accounts create --keystore-path=$HOME/validator and enter those values as inputs

**Comment by wgknowles** [comment]
partially resolved by #116

**Comment by wgknowles** [comment]
resolved
